### PR TITLE
Adjust dependencies to reflect dev 1.1.7

### PR DESCRIPTION
**Pull request by sssangha**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Review by dbekaert — APPROVED** [review]
LGTM @sssangha. We just need to let the test runs through first. That will run it for various python versions. then need to wait till morning for charlie or joe to review and approve.

How do we run the test-suite is that part of conda? @jhkennedy .
Note that we reworked things to use pytest now.

**Review by dbekaert — CHANGES_REQUESTED** [review]
need to check in with joe and charlie, the test are failing of conda.

**Comment by cmarshak** [comment]
```
Could not solve for environment specs
The following packages are incompatible
├─ python >=3.8,<3.9.0a0  is requested and can be installed;
└─ tile_mate is not installable because there are no viable options
   ├─ tile_mate [0.0.4|0.0.5|0.0.6] would require
   │  └─ python >=3.10  but there are no viable options
   │     ├─ python [3.10.0|3.10.1|...|3.12.3] conflicts with any installable versions previously reported;
   │     └─ python 3.12.0rc3 would require
   │        └─ _python_rc, which does not exist (perhaps a missing channel);
   └─ tile_mate [0.0.7|0.0.8|0.0.9] would require
      └─ python >=3.9  but there are no viable options
         ├─ python [3.10.0|3.10.1|...|3.12.3] conflicts with any installable versions previously reported;
         ├─ python 3.12.0rc3, which cannot be installed (as previously explained);
         └─ python [3.9.0|3.9.1|...|3.9.9] conflicts with any installable versions previously reported.
```

The package [`tile-mate`](https://github.com/OPERA-Cal-Val/tile-mate) which I maintain (delighted it is being used!) does not support 3.8. I am not going to change this right now.

I would just modify the conda recipe here appropriately.

**Comment by cmarshak** [comment]
There are other errors in python builds >= 3.9 that I cannot parse. I guess they might be related to actions finishing if there is 1 failure, but not sure.

**Comment by sssangha** [comment]
> ```
> Could not solve for environment specs
> The following packages are incompatible
> ├─ python >=3.8,<3.9.0a0  is requested and can be installed;
> └─ tile_mate is not installable because there are no viable options
>    ├─ tile_mate [0.0.4|0.0.5|0.0.6] would require
>    │  └─ python >=3.10  but there are no viable options
>    │     ├─ python [3.10.0|3.10.1|...|3.12.3] conflicts with any installable versions previously reported;
>    │     └─ python 3.12.0rc3 would require
>    │        └─ _python_rc, which does not exist (perhaps a missing channel);
>    └─ tile_mate [0.0.7|0.0.8|0.0.9] would require
>       └─ python >=3.9  but there are no viable options
>          ├─ python [3.10.0|3.10.1|...|3.12.3] conflicts with any installable versions previously reported;
>          ├─ python 3.12.0rc3, which cannot be installed (as previously explained);
>          └─ python [3.9.0|3.9.1|...|3.9.9] conflicts with any installable versions previously reported.
> ```
> 
> The package [`tile-mate`](https://github.com/OPERA-Cal-Val/tile-mate) which I maintain (delighted it is being used!) does not support 3.8. I am not going to change this right now.
> 
> I would just modify the conda recipe here appropriately.

Strange, in my own local build from dev (using the environment [yml](https://github.com/aria-tools/ARIA-tools/blob/dev/environment.yml)) I had a successful stable build with python `3.12.3`. Not sure why I can't replicate this on my own end locally

**Comment by cmarshak** [comment]
Does not support `python 3.8` - so that checks out. This is checking all the supported python version.

**Comment by jhkennedy** [comment]
@sssangha you can do it in the recipe here; I'm in a meeting be we can chat about it at our check-in

**Comment by cmarshak** [comment]
https://github.com/conda-forge/aria-tools-feedstock/blob/71e5b09de9359aae40c590ea47f285417061e0b4/recipe/meta.yaml#L34

**Comment by jhkennedy** [comment]
@cmarshak no. Not in compiled recipes.

You'll want to adjust the skip here:
https://github.com/conda-forge/aria-tools-feedstock/pull/9/files#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9aR18

**Comment by sssangha** [comment]
Ok looks like it works! Thanks everyone.

We can talk about this more at the coordination meeting, but I had one more question. We had a couple more minor patches after the official v.1.1.7 release of ARIA-tools. So is there any straightforward, appropriate way to integrate those patches into this conda release? Would it involve updating the existing release? We'd want to avoid cutting a new release, if possible.

If it's too involved, then we could very well just proceed with this release, which is stable. Thanks again!

**Comment by jhkennedy** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
